### ISSUE TITLE
jquery__event_type_pointerpressrelease: pointerpress event is triggered twice on each mousedown in IE10.

### ISSUE THREAD

**Issue by dfilatov** [bem/bem-core#505] opened 2014-04-18 16:06 UTC
``` js
$(document).on('pointerpress', function() {
    console.log('pointerpress');
});
```

**Comment by narqo** [comment] 2014-04-23 15:41
@dfilatov I've added a test for `pointerpressrelease` in the [issues/505@v2](https://github.com/bem/bem-core/tree/issues/505%40v2) branch. Could you check it in your IE version, because I can't reproduce this issue.

``` shell
› git co issues/505@v2
› bem server 
› open desktop.tests/jquery__event_type_pointerpressrelease/simple/simple.html
```

See [query__event_type_pointerpressrelease.tests/simple.blocks/example/example.js](https://github.com/bem/bem-core/blob/issues/505%40v2/common.blocks/jquery/__event/_type/jquery__event_type_pointerpressrelease.tests/simple.blocks/example/example.js) for code.

There was a bug in our `.bem/make.js` / `bem-pr` configuration, so `desktop.tests/`'s blocks were included twice :)

**Comment by narqo** [comment] 2014-04-23 21:59
@dfilatov could you check this https://github.com/narqo/test-pointerevents? I'm not sure, but it looks like `doc.on('pointerrelease', <handler>)` has strange behavior in any browser there. 

On `<button>` press, I get two messages in console:

```
› press
› release
```

while in my opinion there should be only first one. 

Actually I understand why this is happening, but I don't understand is it correct?

**Comment by dfilatov** [comment] 2014-04-24 17:53
Yes, it's a very strange behaviour.
But, when I replaced `pointerpress` by `mousedown` and `pointerrelease` by `mouseup` -- all became to work as it was expected. I thought that `pointerpress/pointerrelease` events are transparent wrappers around `mousedown/mouseup` events for desktops, but ... (

**Comment by narqo** [comment] 2014-04-24 20:17
There is a bug in @deepsweet's [jquery-pointerpressrelease.js](https://github.com/deepsweet/jquery-pointerpressrelease/blob/master/src/jquery-pointerpressrelease.js#L155-L156) implementation, which, I think, was [fixed in bem-core](https://github.com/bem/bem-core/blob/v2/common.blocks/jquery/__event/_type/jquery__event_type_pointerpressrelease.js#L144-L163), but haven't been backported to upstream.

I'll try to dig the original issue more deeply

**Closed as completed** 2014-04-25 17:19 UTC
Labels: v2
