### ISSUE TITLE
Rewrite jsdoc in the likeness of bem-components

### ISSUE THREAD

**Issue by gela-d** [bem/bem-core#1001] opened 2015-05-05 11:02 UTC
The current jsdoc is outdated and we need jsdoc in the likeness of bem-components for the correct jsdoc's display on bem.info

**Comment by gela-d** [comment] 2015-05-05 11:02
cc @tadatuta @aristov

**Comment by tadatuta** [comment] 2015-05-05 11:05
duplicate of https://github.com/bem/bem-core/issues/1000

**Closed as completed by tadatuta** 2015-05-05 11:05 UTC
